-- ==============================================================================
-- Migration: Phase 11 — SEO Autopilot + Opportunity Engine
-- Date: 2026-09-16
-- Description:
--   Creates tables, indexes, and RLS policies for:
--     1. seo_opportunities: Structured SEO opportunities generated by the opportunity engine.
--     2. seo_autopilot_settings: Autopilot configuration and status per website.
--     3. seo_autopilot_activity: Audit log of autopilot scans, recommendations, and execution.
-- ==============================================================================

-- 1. Create enum types if not exists
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'seo_opportunity_status') THEN
    CREATE TYPE seo_opportunity_status AS ENUM ('new', 'viewed', 'in_progress', 'completed', 'dismissed');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'seo_opportunity_priority') THEN
    CREATE TYPE seo_opportunity_priority AS ENUM ('Critical', 'High', 'Medium', 'Low');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'seo_autopilot_status') THEN
    CREATE TYPE seo_autopilot_status AS ENUM ('active', 'paused');
  END IF;
END $$;

-- 2. Create seo_opportunities table
CREATE TABLE IF NOT EXISTS public.seo_opportunities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  website_id UUID NOT NULL REFERENCES public.websites(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- technical_seo, content, gsc, internal_linking, local_seo, blog_content, third_party, monitoring
  category TEXT NOT NULL, -- missing_meta, thin_content, low_ctr, orphan_page, nap_issue, etc.
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  affected_page TEXT,
  affected_keyword TEXT,
  severity TEXT NOT NULL DEFAULT 'medium', -- critical, high, medium, low
  impact TEXT NOT NULL DEFAULT 'medium', -- high, medium, low
  effort TEXT NOT NULL DEFAULT 'low', -- low, medium, high
  priority public.seo_opportunity_priority NOT NULL DEFAULT 'Medium',
  priority_score NUMERIC(5, 2) NOT NULL DEFAULT 50.00,
  source TEXT NOT NULL DEFAULT 'audit', -- audit, gsc, blog, internal_links, local_seo, monitoring, third_party
  recommended_action TEXT NOT NULL,
  action_type TEXT, -- ai_fix_meta, create_blog_post, apply_internal_link, update_local_schema, etc.
  action_payload JSONB DEFAULT '{}'::jsonb,
  status public.seo_opportunity_status NOT NULL DEFAULT 'new',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for fast querying
CREATE INDEX IF NOT EXISTS idx_seo_opportunities_website_status ON public.seo_opportunities(website_id, status);
CREATE INDEX IF NOT EXISTS idx_seo_opportunities_priority_score ON public.seo_opportunities(website_id, priority_score DESC);
CREATE INDEX IF NOT EXISTS idx_seo_opportunities_category ON public.seo_opportunities(website_id, category);

-- Unique index to prevent duplicate active/open opportunities for the same website, category & page
CREATE UNIQUE INDEX IF NOT EXISTS idx_seo_opportunities_unique_open
  ON public.seo_opportunities(website_id, category, COALESCE(affected_page, ''))
  WHERE status IN ('new', 'viewed', 'in_progress');

-- 3. Create seo_autopilot_settings table
CREATE TABLE IF NOT EXISTS public.seo_autopilot_settings (
  website_id UUID PRIMARY KEY REFERENCES public.websites(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status public.seo_autopilot_status NOT NULL DEFAULT 'active',
  scan_frequency TEXT NOT NULL DEFAULT 'weekly', -- daily, weekly, monthly
  auto_stage_safe_fixes BOOLEAN NOT NULL DEFAULT true,
  notify_on_critical BOOLEAN NOT NULL DEFAULT true,
  last_scanned_at TIMESTAMPTZ,
  next_scan_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_seo_autopilot_user ON public.seo_autopilot_settings(user_id);

-- 4. Create seo_autopilot_activity table
CREATE TABLE IF NOT EXISTS public.seo_autopilot_activity (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  website_id UUID NOT NULL REFERENCES public.websites(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL, -- scan_completed, opportunity_discovered, action_staged, action_executed, action_dismissed
  title TEXT NOT NULL,
  details TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_seo_autopilot_activity_website ON public.seo_autopilot_activity(website_id, created_at DESC);

-- 5. Enable Row Level Security
ALTER TABLE public.seo_opportunities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seo_autopilot_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seo_autopilot_activity ENABLE ROW LEVEL SECURITY;

-- 6. Strict User Ownership RLS Policies
-- RLS: seo_opportunities
DROP POLICY IF EXISTS "Users can manage their own website SEO opportunities" ON public.seo_opportunities;
CREATE POLICY "Users can manage their own website SEO opportunities"
  ON public.seo_opportunities
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- RLS: seo_autopilot_settings
DROP POLICY IF EXISTS "Users can manage their own website SEO autopilot settings" ON public.seo_autopilot_settings;
CREATE POLICY "Users can manage their own website SEO autopilot settings"
  ON public.seo_autopilot_settings
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- RLS: seo_autopilot_activity
DROP POLICY IF EXISTS "Users can view their own website SEO autopilot activity" ON public.seo_autopilot_activity;
CREATE POLICY "Users can view their own website SEO autopilot activity"
  ON public.seo_autopilot_activity
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 7. Trigger to automatically update updated_at on opportunity changes
CREATE OR REPLACE FUNCTION public.update_seo_opportunities_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_seo_opportunities_updated_at ON public.seo_opportunities;
CREATE TRIGGER trg_seo_opportunities_updated_at
  BEFORE UPDATE ON public.seo_opportunities
  FOR EACH ROW
  EXECUTE FUNCTION public.update_seo_opportunities_updated_at();

DROP TRIGGER IF EXISTS trg_seo_autopilot_settings_updated_at ON public.seo_autopilot_settings;
CREATE TRIGGER trg_seo_autopilot_settings_updated_at
  BEFORE UPDATE ON public.seo_autopilot_settings
  FOR EACH ROW
  EXECUTE FUNCTION public.update_seo_opportunities_updated_at();
